In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Day7_Student_Dataset.csv")

df.head()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
0,1001,Aarav Sharma,19,Data Science,87.0,91.0,Srinagar
1,1002,Zoya Khan,20,AI,92.0,95.0,Delhi
2,1003,Rohan Mehta,18,Computer Science,76.0,82.0,Mumbai
3,1004,Ananya Singh,21,Data Science,81.0,88.0,Srinagar
4,1005,Kabir Ali,19,AI,69.0,76.0,Lucknow

In [3]:
df.tail()

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
20,1021,Aman Kumar,18,Computer Science,74.0,78.0,Delhi
21,1022,Alina Shah,19,Data Science,96.0,98.0,Srinagar
22,1023,Nikhil Sood,22,AI,78.0,83.0,Pune
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
24,1025,Reyansh Jain,21,Data Science,80.0,84.0,Kolkata

In [4]:
df.sample(5)

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
17,1018,Manya Rao,22,Computer Science,70.0,74.0,Bengaluru
23,1024,Maryam Khan,20,Computer Science,85.0,88.0,Hyderabad
11,1012,Aisha Mir,19,Computer Science,68.0,72.0,Delhi
19,1020,Priya Menon,21,AI,90.0,91.0,Chennai
9,1010,Mehak Bhat,21,Data Science,79.0,90.0,Srinagar

In [5]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])
print("Shape:", df.shape)

Number of rows: 25
Number of columns: 7
Shape: (25, 7)

In [6]:
print("Columns:")
print(df.columns)

Columns:
Index(['Student_ID', 'Name', 'Age', 'Course', 'Marks', 'Attendance_Percentage',
       'City'],
      dtype='object')

In [7]:
print("Index:")
print(df.index)

Index:
RangeIndex(start=0, stop=25, step=1)

In [8]:
print("Data Types:")
print(df.dtypes)

Data Types:
Student_ID                 int64
Name                      object
Age                        int64
Course                    object
Marks                    float64
Attendance_Percentage    float64
City                      object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             25 non-null     int64
 1   Name                   25 non-null     object
 2   Age                    25 non-null     int64
 3   Course                 25 non-null     object
 4   Marks                  24 non-null     float64
 5   Attendance_Percentage  24 non-null     float64
 6   City                   24 non-null     object
dtypes: float64(2), int64(2), object(3)
memory usage: 1.5+ KB

In [10]:
df.describe()

        Student_ID        Age      Marks  Attendance_Percentage
count    25.000000  25.000000  24.000000              24.000000
mean   1013.000000  20.000000  82.250000              87.083333
std       7.359801   1.414214   8.689074               7.252686
min    1001.000000  18.000000  68.000000              72.000000
25%    1007.000000  19.000000  75.500000              82.750000
50%    1013.000000  20.000000  82.500000              88.000000
75%    1019.000000  21.000000  89.250000              92.250000
max    1025.000000  23.000000  96.000000              98.000000

In [11]:
df.describe(include="all")

,Student_ID,Name,Age,Course,Marks,Attendance_Percentage,City
count,25.000000,25,25.000000,25,24.000000,24.000000,24
unique,NaN,25,NaN,3,NaN,NaN,13
top,NaN,Aarav Sharma,NaN,Data Science,NaN,NaN,Srinagar
freq,NaN,1,NaN,9,NaN,NaN,6
mean,1013.000000,NaN,20.000000,NaN,82.250000,87.083333,NaN
std,7.359801,NaN,1.414214,NaN,8.689074,7.252686,NaN
min,1001.000000,NaN,18.000000,NaN,68.000000,72.000000,NaN
25%,1007.000000,NaN,19.000000,NaN,75.500000,82.750000,NaN
50%,1013.000000,NaN,20.000000,NaN,82.500000,88.000000,NaN
75%,1019.000000,NaN,21.000000,NaN,89.250000,92.250000,NaN
max,1025.000000,NaN,23.000000,NaN,96.000000,98.000000,NaN

In [12]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Student_ID               0
Name                     0
Age                      0
Course                   0
Marks                    1
Attendance_Percentage    1
City                     1
dtype: int64

In [13]:
print("Total Missing Values:", df.isnull().sum().sum())

Total Missing Values: 3

The dataset contains 25 student records with 7 features covering student identification, personal information, academic performance, attendance, and location. The dataset contains both numerical and categorical data. Most columns are complete, but missing values are present in Marks, Attendance_Percentage, and City. The dataset provides a suitable foundation for further data cleaning, analysis, and visualization using Pandas.