In [3]:
import pandas as pd
import numpy as np

In [4]:
file_path = "Day11_Messy_Company_Employee_Dataset.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Dataset Shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Dataset Shape: (157, 12)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [6]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
df.info()

Number of Rows: 157
Number of Columns: 12

Column Names:
['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age', 'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City', 'Performance_Score', 'Work_Mode']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [7]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Employee_ID,157,150,EMP0075,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Employee_Name,157,130,Nikhil Das,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Department,152,10,Marketing,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Job_Title,157,23,Data Scientist,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,153.0,NaN,NaN,NaN,38.130719,9.361661,21.0,30.0,39.0,46.0,52.0
Gender,152,5,Male,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Annual_Salary,152.0,NaN,NaN,NaN,89240.592105,22626.172309,43331.0,71198.5,90046.5,107328.0,162942.0
Experience_Years,154.0,NaN,NaN,NaN,8.990909,4.983874,0.6,4.45,9.35,13.2,17.4
Joining_Date,157,147,2025-08-17,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,152,13,Chandigarh,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Performance_Score,154.0,NaN,NaN,NaN,3.525974,0.930233,2.0,3.0,4.0,4.0,5.0
Work_Mode,155,5,Remote,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
original_rows = df.shape[0]
original_columns = df.shape[1]

original_missing = df.isnull().sum().sum()
original_duplicates = df.duplicated().sum()

print("========== BEFORE CLEANING ==========")
print("Rows:", original_rows)
print("Columns:", original_columns)
print("Missing Values:", original_missing)
print("Duplicate Records:", original_duplicates)

========== BEFORE CLEANING ==========
Rows: 157
Columns: 12
Missing Values: 32
Duplicate Records: 7

In [9]:
missing_report = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

display(missing_report)

                   Missing Values  Missing Percentage
Employee_ID                     0                0.00
Employee_Name                   0                0.00
Department                      5                3.18
Job_Title                       0                0.00
Age                             4                2.55
Gender                          5                3.18
Annual_Salary                   5                3.18
Experience_Years                3                1.91
Joining_Date                    0                0.00
City                            5                3.18
Performance_Score               3                1.91
Work_Mode                       2                1.27

In [10]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

if duplicate_count > 0:
    display(df[df.duplicated(keep=False)].sort_values("Employee_ID"))

Number of duplicate records: 7

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
70,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
78,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
11,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
25,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
92,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
85,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
112,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote

In [11]:
categorical_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]

for column in categorical_columns:
    print("\n" + "=" * 50)
    print(column)
    print(df[column].value_counts(dropna=False))

==================================================
Department
Department
Marketing           23
Engineering         21
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
NaN                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

==================================================
Gender
Gender
Male      75
Female    68
Other      7
NaN        5
female     1
MALE       1
Name: count, dtype: int64

==================================================
City
City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Srinagar      13
Bengaluru     12
Delhi         11
Chennai       10
Kolkata        9
NaN            5
delhi          1
DELHI          1
Delhi          1
Name: count, dtype: int64

==================================================
Work_Mode
Work_Mode
Remote    56
Hybrid    50
Office    47
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [12]:
text_columns = df.select_dtypes(include="object").columns

for column in text_columns:
    df[column] = df[column].str.strip()

print("Extra spaces removed from text columns.")

Extra spaces removed from text columns.

In [13]:
df["Department"] = df["Department"].replace({
    "ENGINEERING": "Engineering",
    "engineering": "Engineering"
})

print(df["Department"].value_counts(dropna=False))

Department
Marketing           23
Engineering         23
Customer Success    20
Finance             19
Sales               19
Operations          17
Human Resources     16
Data & Analytics    15
NaN                  5
Name: count, dtype: int64

In [14]:
df["Gender"] = df["Gender"].replace({
    "female": "Female",
    "MALE": "Male"
})

print(df["Gender"].value_counts(dropna=False))

Gender
Male      76
Female    69
Other      7
NaN        5
Name: count, dtype: int64

In [15]:
df["City"] = df["City"].replace({
    "delhi": "Delhi",
    "DELHI": "Delhi"
})

print(df["City"].value_counts(dropna=False))

City
Chandigarh    24
Pune          23
Jaipur        18
Mumbai        15
Hyderabad     14
Delhi         14
Srinagar      13
Bengaluru     12
Chennai       10
Kolkata        9
NaN            5
Name: count, dtype: int64

In [16]:
df["Work_Mode"] = df["Work_Mode"].replace({
    "REMOTE": "Remote",
    "remote": "Remote"
})

print(df["Work_Mode"].value_counts(dropna=False))

Work_Mode
Remote    58
Hybrid    50
Office    47
NaN        2
Name: count, dtype: int64

In [17]:
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicates before cleaning:", duplicates_before)
print("Duplicates after cleaning:", duplicates_after)
print("Rows after removing duplicates:", len(df))

Duplicates before cleaning: 7
Duplicates after cleaning: 0
Rows after removing duplicates: 150

In [18]:
print("Missing values after removing duplicates:")

display(
    pd.DataFrame({
        "Missing Values": df.isnull().sum(),
        "Percentage": (
            df.isnull().sum() / len(df) * 100
        ).round(2)
    })
)

Missing values after removing duplicates:

                   Missing Values  Percentage
Employee_ID                     0        0.00
Employee_Name                   0        0.00
Department                      5        3.33
Job_Title                       0        0.00
Age                             4        2.67
Gender                          5        3.33
Annual_Salary                   4        2.67
Experience_Years                3        2.00
Joining_Date                    0        0.00
City                            5        3.33
Performance_Score               3        2.00
Work_Mode                       2        1.33

In [19]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]

for column in numeric_columns:
    median_value = df[column].median()
    df[column] = df[column].fillna(median_value)

print("Numeric missing values filled using median.")

Numeric missing values filled using median.

In [20]:
categorical_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]

for column in categorical_columns:
    mode_value = df[column].mode()[0]
    df[column] = df[column].fillna(mode_value)

print("Categorical missing values filled using mode.")

Categorical missing values filled using mode.

In [21]:
df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)

print(df["Joining_Date"].dtype)

datetime64[ns]

In [22]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Annual_Salary"] = pd.to_numeric(df["Annual_Salary"], errors="coerce")
df["Experience_Years"] = pd.to_numeric(df["Experience_Years"], errors="coerce")
df["Performance_Score"] = pd.to_numeric(df["Performance_Score"], errors="coerce")

print(df.dtypes)

Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

In [23]:
print("========== FINAL MISSING VALUE CHECK ==========")

final_missing = df.isnull().sum()

display(
    pd.DataFrame({
        "Missing Values": final_missing,
        "Percentage": (
            final_missing / len(df) * 100
        ).round(2)
    })
)

========== FINAL MISSING VALUE CHECK ==========

                   Missing Values  Percentage
Employee_ID                     0         0.0
Employee_Name                   0         0.0
Department                      0         0.0
Job_Title                       0         0.0
Age                             0         0.0
Gender                          0         0.0
Annual_Salary                   0         0.0
Experience_Years                0         0.0
Joining_Date                    0         0.0
City                            0         0.0
Performance_Score               0         0.0
Work_Mode                       0         0.0

In [24]:
print("Remaining duplicate records:", df.duplicated().sum())

Remaining duplicate records: 0

In [26]:
print("========== FINAL DATA TYPES ==========")
print(df.dtypes)

========== FINAL DATA TYPES ==========
Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

In [27]:
for column in ["Department", "Gender", "City", "Work_Mode"]:
    print("\n" + "=" * 50)
    print(column)
    print(df[column].value_counts())

==================================================
Department
Department
Engineering         28
Marketing           22
Customer Success    20
Sales               18
Human Resources     16
Operations          16
Data & Analytics    15
Finance             15
Name: count, dtype: int64

==================================================
Gender
Gender
Male      77
Female    66
Other      7
Name: count, dtype: int64

==================================================
City
City
Pune          28
Chandigarh    22
Jaipur        17
Delhi         14
Hyderabad     14
Mumbai        13
Srinagar      13
Bengaluru     11
Chennai        9
Kolkata        9
Name: count, dtype: int64

==================================================
Work_Mode
Work_Mode
Remote    58
Hybrid    48
Office    44
Name: count, dtype: int64

In [28]:
display(df.describe().T)

,count,mean,min,25%,50%,75%,max,std
Age,150.0,38.113333,21.0,31.0,39.0,46.0,52.0,9.24574
Annual_Salary,150.0,88854.833333,43331.0,71123.5,89302.0,104693.25,162942.0,22354.618782
Experience_Years,150.0,8.916667,0.6,4.45,9.2,13.175,17.4,4.929658
Joining_Date,150,2021-04-06 15:12:00,2017-01-04 00:00:00,2018-12-23 00:00:00,2021-01-05 00:00:00,2023-08-15 18:00:00,2026-01-06 00:00:00,NaN
Performance_Score,150.0,3.56,2.0,3.0,4.0,4.0,5.0,0.923082

In [29]:
final_rows = df.shape[0]
final_columns = df.shape[1]
final_missing = df.isnull().sum().sum()
final_duplicates = df.duplicated().sum()

comparison = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Records"
    ],
    "Before Cleaning": [
        original_rows,
        original_columns,
        original_missing,
        original_duplicates
    ],
    "After Cleaning": [
        final_rows,
        final_columns,
        final_missing,
        final_duplicates
    ]
})

display(comparison)

              Metric  Before Cleaning  After Cleaning
0               Rows              157             150
1            Columns               12              12
2     Missing Values               32               0
3  Duplicate Records                7               0