In [ ]:
# Day 9 - Processed E-commerce Dataset

import pandas as pd

# --------------------------------------------------
# 1. Load the datasets
# --------------------------------------------------

orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products.csv")

print("Orders Dataset:")
display(orders.head())

print("Customers Dataset:")
display(customers.head())

print("Products Dataset:")
display(products.head())


# --------------------------------------------------
# 2. Check the structure of the datasets
# --------------------------------------------------

print("Orders Shape:", orders.shape)
print("Customers Shape:", customers.shape)
print("Products Shape:", products.shape)

print("\nOrders Columns:")
print(orders.columns.tolist())

print("\nCustomers Columns:")
print(customers.columns.tolist())

print("\nProducts Columns:")
print(products.columns.tolist())


# --------------------------------------------------
# 3. Check missing values
# --------------------------------------------------

print("\nMissing Values in Orders:")
print(orders.isnull().sum())

print("\nMissing Values in Customers:")
print(customers.isnull().sum())

print("\nMissing Values in Products:")
print(products.isnull().sum())


# --------------------------------------------------
# 4. Merge Orders with Customers
# --------------------------------------------------

processed_data = pd.merge(
    orders,
    customers,
    on="Customer_ID",
    how="left"
)

print("\nAfter merging Orders and Customers:")
display(processed_data.head())


# --------------------------------------------------
# 5. Merge with Products
# --------------------------------------------------

processed_data = pd.merge(
    processed_data,
    products,
    on="Product_ID",
    how="left"
)

print("\nAfter merging all datasets:")
display(processed_data.head())


# --------------------------------------------------
# 6. Demonstrate concat()
# --------------------------------------------------

# Create a small DataFrame from the first few rows
sample_1 = processed_data.head(3)
sample_2 = processed_data.tail(3)

combined_sample = pd.concat(
    [sample_1, sample_2],
    ignore_index=True
)

print("\nDemonstration of concat():")
display(combined_sample)


# --------------------------------------------------
# 7. Convert Order Date to DateTime
# --------------------------------------------------

processed_data["Order_Date"] = pd.to_datetime(
    processed_data["Order_Date"],
    errors="coerce"
)

print("\nOrder Date after conversion:")
print(processed_data["Order_Date"].head())


# --------------------------------------------------
# 8. Extract DateTime information
# --------------------------------------------------

processed_data["Order_Year"] = processed_data["Order_Date"].dt.year
processed_data["Order_Month"] = processed_data["Order_Date"].dt.month
processed_data["Order_Day"] = processed_data["Order_Date"].dt.day
processed_data["Order_Day_Name"] = processed_data["Order_Date"].dt.day_name()


# --------------------------------------------------
# 9. Use apply() to create a useful column
# --------------------------------------------------

processed_data["Product_Name_Clean"] = processed_data["Product_Name"].apply(
    lambda x: str(x).strip().title()
)


# --------------------------------------------------
# 10. Calculate Total Sales using apply()
# --------------------------------------------------

processed_data["Calculated_Sales"] = processed_data.apply(
    lambda row: row["Quantity"] * row["Unit_Price"],
    axis=1
)


# --------------------------------------------------
# 11. Create a Sales Category
# --------------------------------------------------

processed_data["Sales_Category"] = processed_data["Calculated_Sales"].apply(
    lambda x: "High" if x >= 5000
    else "Medium" if x >= 2000
    else "Low"
)


# --------------------------------------------------
# 12. Select useful columns
# --------------------------------------------------

final_columns = [
    "Order_ID",
    "Order_Date",
    "Order_Year",
    "Order_Month",
    "Order_Day",
    "Order_Day_Name",
    "Customer_ID",
    "Product_ID",
    "Product_Name_Clean",
    "Quantity",
    "Unit_Price",
    "Calculated_Sales",
    "Sales_Category"
]

# Keep only columns that actually exist
final_columns = [
    column for column in final_columns
    if column in processed_data.columns
]

final_data = processed_data[final_columns].copy()


# --------------------------------------------------
# 13. Display the final processed dataset
# --------------------------------------------------

print("\nFinal Processed Dataset:")
display(final_data.head(10))

print("\nFinal Dataset Shape:")
print(final_data.shape)


# --------------------------------------------------
# 14. Check final data types
# --------------------------------------------------

print("\nFinal Dataset Data Types:")
print(final_data.dtypes)


# --------------------------------------------------
# 15. Check missing values
# --------------------------------------------------

print("\nMissing Values in Final Dataset:")
print(final_data.isnull().sum())


# --------------------------------------------------
# 16. Export the processed dataset
# --------------------------------------------------

final_data.to_csv(
    "Processed_Ecommerce_Dataset.csv",
    index=False
)

print("\nProcessed dataset exported successfully.")


# --------------------------------------------------
# 17. Read the exported file to verify
# --------------------------------------------------

verification = pd.read_csv("Processed_Ecommerce_Dataset.csv")

print("\nExported Dataset:")
display(verification.head())

print("\nExported Dataset Shape:")
print(verification.shape)

Orders Dataset:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

Customers Dataset:

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

Products Dataset:

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

Orders Shape: (120, 7)
Customers Shape: (30, 5)
Products Shape: (20, 5)

Orders Columns:
['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']

Customers Columns:
['Customer_ID', 'Customer_Name', 'City', 'Region', 'Membership_Type']

Products Columns:
['Product_ID', 'Product_Name', 'Category', 'Unit_Price', 'Brand']

Missing Values in Orders:
Order_ID          0
Order_Date        0
Customer_ID       0
Product_ID        0
Quantity          0
Payment_Method    0
Order_Status      0
dtype: int64

Missing Values in Customers:
Customer_ID        0
Customer_Name      0
City               0
Region             0
Membership_Type    0
dtype: int64

Missing Values in Products:
Product_ID      0
Product_Name    0
Category        0
Unit_Price      0
Brand           0
dtype: int64

After merging Orders and Customers:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

After merging all datasets:

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

Demonstration of concat():

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Atomic Habits,Books,599,MindReads
4,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular,Cricket Bat,Sports,2499,BatPro
5,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular,Dumbbell Set,Sports,1999,StrongFit

Order Date after conversion:
0   2026-02-19
1   2026-01-25
2   2026-02-26
3   2026-03-04
4   2026-03-29
Name: Order_Date, dtype: datetime64[ns]

Final Processed Dataset:

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Day,Order_Day_Name,Customer_ID,Product_ID,Product_Name_Clean,Quantity,Unit_Price,Calculated_Sales,Sales_Category
0,O0001,2026-02-19,2026,2,19,Thursday,C027,P019,Cricket Bat,2,2499,4998,Medium
1,O0002,2026-01-25,2026,1,25,Sunday,C006,P003,Wireless Mouse,2,899,1798,Low
2,O0003,2026-02-26,2026,2,26,Thursday,C015,P004,Smart Watch,1,3299,3299,Medium
3,O0004,2026-03-04,2026,3,4,Wednesday,C024,P015,Machine Learning Basics,3,999,2997,Medium
4,O0005,2026-03-29,2026,3,29,Sunday,C025,P009,Coffee Maker,5,3499,17495,High
5,O0006,2026-02-09,2026,2,9,Monday,C003,P018,Football,3,799,2397,Medium
6,O0007,2026-02-10,2026,2,10,Tuesday,C011,P003,Wireless Mouse,3,899,2697,Medium
7,O0008,2026-03-27,2026,3,27,Friday,C020,P005,Power Bank,4,1199,4796,Medium
8,O0009,2026-03-13,2026,3,13,Friday,C024,P009,Coffee Maker,2,3499,6998,High
9,O0010,2026-03-05,2026,3,5,Thursday,C026,P005,Power Bank,2,1199,2398,Medium

Final Dataset Shape:
(120, 13)

Final Dataset Data Types:
Order_ID                      object
Order_Date            datetime64[ns]
Order_Year                     int32
Order_Month                    int32
Order_Day                      int32
Order_Day_Name                object
Customer_ID                   object
Product_ID                    object
Product_Name_Clean            object
Quantity                       int64
Unit_Price                     int64
Calculated_Sales               int64
Sales_Category                object
dtype: object

Missing Values in Final Dataset:
Order_ID              0
Order_Date            0
Order_Year            0
Order_Month           0
Order_Day             0
Order_Day_Name        0
Customer_ID           0
Product_ID            0
Product_Name_Clean    0
Quantity              0
Unit_Price            0
Calculated_Sales      0
Sales_Category        0
dtype: int64

Processed dataset exported successfully.

Exported Dataset:

,Order_ID,Order_Date,Order_Year,Order_Month,Order_Day,Order_Day_Name,Customer_ID,Product_ID,Product_Name_Clean,Quantity,Unit_Price,Calculated_Sales,Sales_Category
0,O0001,2026-02-19,2026,2,19,Thursday,C027,P019,Cricket Bat,2,2499,4998,Medium
1,O0002,2026-01-25,2026,1,25,Sunday,C006,P003,Wireless Mouse,2,899,1798,Low
2,O0003,2026-02-26,2026,2,26,Thursday,C015,P004,Smart Watch,1,3299,3299,Medium
3,O0004,2026-03-04,2026,3,4,Wednesday,C024,P015,Machine Learning Basics,3,999,2997,Medium
4,O0005,2026-03-29,2026,3,29,Sunday,C025,P009,Coffee Maker,5,3499,17495,High

Exported Dataset Shape:
(120, 13)